<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '' => '',
    '1 hour included. More {0} per hour' => '1 час включен. Более - {0} в час',
    '10 minutes for free. More {0} per hour.' => '10 минут бесплатно. Более - {0} в час.',
    'About' => 'О нас',
    'All in one...' => 'Все в одном...',
    'All the power of our panel for free. With reasonable limitations, sorry. But you can try the panel - no need to pay.' => '',
    'An {name} is Born' => '',
    'Andrey Klochok' => 'Андрей Клочок',
    'Andrii Vasyliev' => 'Андрей Вавильев',
    'Be Part {br}Of Our{br}Story!' => '',
    'Choose what you prefer. Nothing to install cloud based SaaS solution. Or open source solution installed at your side.' => '',
    'Client profile' => '',
    'Contact' => 'Контакты',
    'Contact Us' => 'Свяжитесь с нами',
    'Customer support' => 'Служба поддержки',
    'DECEMBER 2014' => '',
    'Dashboard' => 'Панель управления',
    'Dedicated Server {0}' => '',
    'Dmitry Naumenko' => 'Дмитрий Науменко',
    'Domains' => 'Домены',
    'Domain {0} per year' => '',
    'Don\'t be shy, drop us an email and say hello! We are a really nice bunch of people :)' => '',
    'Easy' => 'Легко',
    'Features' => '',
    'Includes personalized site and panel. We\'ll do all the necessary integration of your infrastructure with our panel.' => '',
    'Login' => 'Вход',
    'Long time ago...' => 'Давным давно...',
    'MARCH 2015' => '',
    'Modern and responsive design. Nice to look on every device. Easy to use for every task.' => '',
    'NOVEMBER 2014' => '',
    'No monthly fee' => 'Без абонентской платы',
    'No subclients' => 'Нет субклиентов',
    'OAuth2, ABAC, Backup and more ...' => '',
    'One Domain for free. Every next {0} per year' => '',
    'One VDS for free. Every next {0}$2.99 per month' => '',
    'One server for free. Every next {0} per month' => '',
    'Open for integration and extension' => '',
    'Our Amazing Team' => 'Наша замечательная команда',
    'Our Humble Beginnings' => '',
    'Per Month' => 'В месяц',
    'Phase Two Expansion' => 'Второй этап расширения',
    'Pricing' => 'Цены',
    'Pro' => '',
    'Responsive Design and Friendly UX' => 'Адаптивный дизайн и дружелюбной UX',
    'SaaS and Open Source' => 'SaaS и Open Source',
    'Screenshots' => 'Скриншоты',
    'Security and reliability' => 'Безопасность и надежность',
    'Send Message' => 'Отправить сообщение',
    'Servers' => 'Сервера',
    'Slightly limited DNS and other additional services' => 'Немного ограничен DNS и другие дополнительные услуги',
    'Social login' => 'Вход через социальные сети',
    'Start' => 'Старт',
    'Team' => 'Команда',
    'Thank you!' => 'Спасибо!',
    'Transition to Full Service' => 'Переход к полныму набору услуг',
    'Unlimited DNS, Mail and other services' => '',
    'Unlimited additional services' => '',
    'Unlimited subclients' => '',
    'Unlimited support' => '',
    'Up to 999 subclients' => '',
    'Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!' => '',
    'VDS, CDN and other cloud services {0} per month' => '',
    'Website Design' => '',
    'Your message was successfully sent. Our managers will contact you as soon as possible for further details.' => '',
    'Yuriy Myronchuk' => '',
    'for personal use' => '',
    'for resellers' => '',
    'for service providers' => '',
];
