package:
    type:           yii2-extension
    name:           hipanel-com
    title:          hipanel.com site
    headline:       hipanel.com
    keywords:       hipanel, site
    namespace:      hiqdev\sites\hipanelcom
